notas = []
A = int(input("Ingresar nota 1:\n"))
notas.append(A)
B = int(input(f"Nota 1 ingresada = {A}, Ingresar la nota 2: \n"))
notas.append(B)
C = int(input(f"Nota 2 ingresada = {B}, Ingresar la nota 3: \n"))
notas.append(C)
D = int(input(f"Nota 3 ingresada = {C}, Ingresar la nota 4: \n"))
notas.append(D)
E = int(input(f"Nota 4 ingresada = {D}, Ingresar la nota 5: \n"))
notas.append(E)
print(f"Nota 5 ingresada = {E}, Todas las notas ingresadas\n")
print(notas)
print(f'Nota máxima: {max(notas)}\n')
print(f'Nota mínima: {min(notas)}\n')
print(f'Nota promedio: {sum(notas)/5}\n')